/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author p_gen
 */
public class adminAddPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminAddPanel.class.getName());

    /**
     * Creates new form adminAddPanel
     */
    public adminAddPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardLayout = new fancyui.FancyPanel();
        fancyPanel4 = new fancyui.FancyPanel();
        fancyLabel4 = new fancyui.FancyLabel();
        fancyPanel2 = new fancyui.FancyPanel();
        fancyLabel5 = new fancyui.FancyLabel();
        fancyLabel2 = new fancyui.FancyLabel();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyLabel6 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel5 = new fancyui.FancyPanel();
        fancyLabel8 = new fancyui.FancyLabel();
        fancyLabel7 = new fancyui.FancyLabel();
        fancyPanel9 = new fancyui.FancyPanel();
        fancyLabel13 = new fancyui.FancyLabel();
        fancyLabel9 = new fancyui.FancyLabel();
        jLabel3 = new javax.swing.JLabel();
        fancyPanel6 = new fancyui.FancyPanel();
        fancyLabel10 = new fancyui.FancyLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        fancyLabel1 = new fancyui.FancyLabel();
        jLabel2 = new javax.swing.JLabel();
        fancyPanel10 = new fancyui.FancyPanel();
        fancyLabel11 = new fancyui.FancyLabel();
        fancyPanel20 = new fancyui.FancyPanel();
        fancyImage8 = new fancyui.FancyImage();
        fancyButton44 = new fancyui.FancyButton();
        fancyButton45 = new fancyui.FancyButton();
        fancyButton46 = new fancyui.FancyButton();
        fancyButton47 = new fancyui.FancyButton();
        fancyButton48 = new fancyui.FancyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardLayout.setGradientEnabled(false);
        cardLayout.setGradientEnd(new java.awt.Color(0, 0, 20));
        cardLayout.setGradientStart(new java.awt.Color(0, 0, 51));
        cardLayout.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        cardLayout.setSolidBackgroundEnabled(true);

        fancyPanel4.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setBorderThickness(2.0F);
        fancyPanel4.setGradientAngle(65);
        fancyPanel4.setGradientEnd(new java.awt.Color(0, 0, 25));
        fancyPanel4.setGradientStart(new java.awt.Color(76, 0, 153));
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        fancyLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel4.setText("Admin Dashboard");
        fancyLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        fancyPanel2.setBorderColor(new java.awt.Color(102, 51, 255));
        fancyPanel2.setBorderEnabled(true);
        fancyPanel2.setGradientEnd(new java.awt.Color(204, 51, 255));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fancyLabel5.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fancyLabel5.setText("Total Users");
        fancyLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fancyLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N

        fancyLabel2.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel2.setText("fancyLabel2");

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        fancyPanel3.setBorderColor(new java.awt.Color(102, 51, 255));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setGradientEnd(new java.awt.Color(204, 51, 255));
        fancyPanel3.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fancyLabel6.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fancyLabel6.setText("Total Accounts");
        fancyLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fancyLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N

        fancyLabel3.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel3.setText("fancyLabel3");

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        fancyPanel5.setBorderColor(new java.awt.Color(102, 51, 255));
        fancyPanel5.setBorderEnabled(true);
        fancyPanel5.setGradientEnd(new java.awt.Color(204, 51, 255));
        fancyPanel5.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fancyLabel8.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fancyLabel8.setText("Total Deposits");
        fancyLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fancyLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N

        fancyLabel7.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel7.setText("fancyLabel7");

        javax.swing.GroupLayout fancyPanel5Layout = new javax.swing.GroupLayout(fancyPanel5);
        fancyPanel5.setLayout(fancyPanel5Layout);
        fancyPanel5Layout.setHorizontalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addGroup(fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        fancyPanel5Layout.setVerticalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        fancyPanel9.setBorderColor(new java.awt.Color(102, 51, 255));
        fancyPanel9.setBorderEnabled(true);
        fancyPanel9.setGradientEnd(new java.awt.Color(204, 51, 255));
        fancyPanel9.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fancyLabel13.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fancyLabel13.setText("Total Withdrawals");
        fancyLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fancyLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N

        fancyLabel9.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel9.setText("fancyLabel9");

        javax.swing.GroupLayout fancyPanel9Layout = new javax.swing.GroupLayout(fancyPanel9);
        fancyPanel9.setLayout(fancyPanel9Layout);
        fancyPanel9Layout.setHorizontalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        fancyPanel9Layout.setVerticalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Overview of bank activity and key statistics.");

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        fancyPanel6.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel6.setBorderEnabled(true);
        fancyPanel6.setBorderThickness(2.0F);
        fancyPanel6.setGradientAngle(65);
        fancyPanel6.setGradientEnd(new java.awt.Color(0, 0, 51));
        fancyPanel6.setGradientStart(new java.awt.Color(76, 0, 153));
        fancyPanel6.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        fancyLabel10.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel10.setText("Recent Transactions");
        fancyLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(transactionTable);

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addGroup(fancyPanel6Layout.createSequentialGroup()
                        .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel1.setText("Welcome Back,");
        fancyLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here's what's happening to your account today.");

        fancyPanel10.setGradientEnd(new java.awt.Color(125, 24, 175));
        fancyPanel10.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyLabel11.setForeground(new java.awt.Color(255, 204, 0));
        fancyLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-user-24 (1).png")); // NOI18N
        fancyLabel11.setText("User");
        fancyLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel10Layout = new javax.swing.GroupLayout(fancyPanel10);
        fancyPanel10.setLayout(fancyPanel10Layout);
        fancyPanel10Layout.setHorizontalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel10Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fancyPanel10Layout.setVerticalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        fancyPanel20.setBorderEnabled(true);
        fancyPanel20.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel20.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyImage8.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\ChatGPT Image Sep 24, 2026, 04_56_03 PM.png")); // NOI18N
        fancyImage8.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        fancyButton44.setText("Dashboard");
        fancyButton44.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton44.setBorderThickness(3.0F);
        fancyButton44.setDefaultForeground(new java.awt.Color(255, 255, 255));

        fancyButton45.setText("Manage Users");
        fancyButton45.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton45.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyButton45.setBorderThickness(3.0F);
        fancyButton45.setDefaultForeground(new java.awt.Color(255, 255, 255));

        fancyButton46.setText("Manage Accounts");
        fancyButton46.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton46.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyButton46.setBorderThickness(3.0F);
        fancyButton46.setDefaultForeground(new java.awt.Color(255, 255, 255));
        fancyButton46.addActionListener(this::fancyButton46fancyButton4ActionPerformed);

        fancyButton47.setText("Transactions");
        fancyButton47.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton47.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyButton47.setBorderThickness(3.0F);
        fancyButton47.setDefaultForeground(new java.awt.Color(255, 255, 255));
        fancyButton47.addActionListener(this::fancyButton47fancyButton5ActionPerformed);

        fancyButton48.setText("Logout");
        fancyButton48.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton48.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyButton48.setBorderThickness(3.0F);
        fancyButton48.setDefaultForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fancyPanel20Layout = new javax.swing.GroupLayout(fancyPanel20);
        fancyPanel20.setLayout(fancyPanel20Layout);
        fancyPanel20Layout.setHorizontalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(fancyButton46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fancyButton45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fancyButton44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fancyButton47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fancyButton48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fancyPanel20Layout.setVerticalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout cardLayoutLayout = new javax.swing.GroupLayout(cardLayout);
        cardLayout.setLayout(cardLayoutLayout);
        cardLayoutLayout.setHorizontalGroup(
            cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardLayoutLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardLayoutLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fancyPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(fancyPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addComponent(fancyPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        cardLayoutLayout.setVerticalGroup(
            cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayoutLayout.createSequentialGroup()
                .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(fancyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(fancyPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyButton46fancyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton46fancyButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton46fancyButton4ActionPerformed

    private void fancyButton47fancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton47fancyButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton47fancyButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminAddPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyPanel cardLayout;
    private fancyui.FancyButton fancyButton44;
    private fancyui.FancyButton fancyButton45;
    private fancyui.FancyButton fancyButton46;
    private fancyui.FancyButton fancyButton47;
    private fancyui.FancyButton fancyButton48;
    private fancyui.FancyImage fancyImage8;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel11;
    private fancyui.FancyLabel fancyLabel13;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel7;
    private fancyui.FancyLabel fancyLabel8;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel10;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel20;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel5;
    private fancyui.FancyPanel fancyPanel6;
    private fancyui.FancyPanel fancyPanel9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
