import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class adminAddUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminAddUser.class.getName());

    public adminAddUser() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel2 = new fancyui.FancyPanel();
        fullName = new fancyui.FancyTextField();
        registerPass = new fancyui.FancyPasswordField();
        registerBtn = new fancyui.FancyButton();
        fancyLabel5 = new fancyui.FancyLabel();
        confirmPass = new fancyui.FancyPasswordField();
        email2 = new fancyui.FancyTextField();
        email3 = new fancyui.FancyTextField();
        fancyImage1 = new fancyui.FancyImage();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyLabel2 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyLabel4 = new fancyui.FancyLabel();
        fancyLabel6 = new fancyui.FancyLabel();
        registerBtn1 = new fancyui.FancyButton();
        fancyLabel7 = new fancyui.FancyLabel();
        fancyImage2 = new fancyui.FancyImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setGradientEnabled(false);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 20));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 51));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyPanel2.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel2.setBorderEnabled(true);
        fancyPanel2.setBorderThickness(2.0F);
        fancyPanel2.setGradientEnabled(false);
        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 25));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 51));
        fancyPanel2.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        fancyPanel2.setSolidBackgroundEnabled(true);

        fullName.setBackgroundColor(new java.awt.Color(0, 0, 25));
        fullName.setBorderColor(new java.awt.Color(102, 102, 102));
        fullName.setCornerRadius(7);
        fullName.setLeftIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-user-24.png")); // NOI18N
        fullName.setPlaceholder("Full Name");
        fullName.addActionListener(this::fullNameActionPerformed);

        registerPass.setBackgroundColor(new java.awt.Color(0, 0, 25));
        registerPass.setBorderColor(new java.awt.Color(102, 102, 102));
        registerPass.setLeftIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-lock-24.png")); // NOI18N
        registerPass.addActionListener(this::registerPassActionPerformed);

        registerBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        registerBtn.setText("Cancel");
        registerBtn.setBackgroundColor(new java.awt.Color(0, 0, 71));
        registerBtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setGradientEnd(new java.awt.Color(102, 51, 255));
        registerBtn.setGradientStart(new java.awt.Color(0, 0, 102));
        registerBtn.addActionListener(this::registerBtnActionPerformed);

        fancyLabel5.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel5.setText("Add NewUser");
        fancyLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N

        confirmPass.setBackgroundColor(new java.awt.Color(0, 0, 25));
        confirmPass.setBorderColor(new java.awt.Color(102, 102, 102));
        confirmPass.setLeftIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-lock-24.png")); // NOI18N
        confirmPass.setPlaceholder("Confim Password");
        confirmPass.addActionListener(this::confirmPassActionPerformed);

        email2.setBackgroundColor(new java.awt.Color(0, 0, 25));
        email2.setBorderColor(new java.awt.Color(102, 102, 102));
        email2.setCornerRadius(7);
        email2.setPlaceholder("Create pin 4 only");
        email2.addActionListener(this::email2ActionPerformed);

        email3.setBackgroundColor(new java.awt.Color(0, 0, 25));
        email3.setBorderColor(new java.awt.Color(102, 102, 102));
        email3.setCornerRadius(7);
        email3.setPlaceholder("Email Address");
        email3.addActionListener(this::email3ActionPerformed);

        fancyImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\ChatGPT Image Sep 24, 2026, 04_56_03 PM.png")); // NOI18N
        fancyImage1.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        fancyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel1.setText("Password");
        fancyLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        fancyLabel2.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel2.setText("Full name");
        fancyLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        fancyLabel3.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel3.setText("PIN");
        fancyLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        fancyLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel4.setText("Confirm Password");
        fancyLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        fancyLabel6.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel6.setText("Email Address");
        fancyLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        registerBtn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        registerBtn1.setText("Save User");
        registerBtn1.setBackgroundColor(new java.awt.Color(51, 0, 153));
        registerBtn1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerBtn1.setGradientEnabled(true);
        registerBtn1.setGradientEnd(new java.awt.Color(102, 51, 255));
        registerBtn1.setGradientStart(new java.awt.Color(0, 0, 102));
        registerBtn1.addActionListener(this::registerBtn1ActionPerformed);

        fancyLabel7.setForeground(new java.awt.Color(204, 204, 204));
        fancyLabel7.setText("Fill in the details to add a new user to the system.");

        fancyImage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-add-user-100.png")); // NOI18N
        fancyImage2.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel2Layout.createSequentialGroup()
                                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(registerPass, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(fullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(confirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                                        .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(192, 192, 192))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                                .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                                        .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(fancyPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addComponent(registerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 346, Short.MAX_VALUE))))
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(registerPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameActionPerformed

    private void registerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPassActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
   new adminAddUser().setVisible(true);
   this.dispose();
    }//GEN-LAST:event_registerBtnActionPerformed

    private void confirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassActionPerformed

    private void email2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email2ActionPerformed

    private void email3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email3ActionPerformed

    private void registerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtn1ActionPerformed
     
    String name = fullName.getText().trim();
    String email = email3.getText().trim();
    String password = registerPass.getText();
    String confirmPassword = confirmPass.getText();
    String pin = email2.getText().trim();

    if (name.isEmpty() || email.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || pin.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }
    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match.");
        return;
    }
    if (!pin.matches("\\d{4}")) {
        JOptionPane.showMessageDialog(this, "PIN must be exactly 4 digits.");
        return;
    }
    String sql = "INSERT INTO users " + "(fullname, email, password, role, pin) "+ "VALUES (?, ?, ?, ?, ?)";
 
    try (Connection conn = new DBconnection().connect();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, name);
        ps.setString(2, email);
        ps.setString(3, password);
        ps.setString(4, "customer");
        ps.setString(5, pin);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "User added successfully!");

        new adminUserManagement().setVisible(true);
        this.dispose();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error adding user: " + e.getMessage());
    }
    }//GEN-LAST:event_registerBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminAddUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyPasswordField confirmPass;
    private fancyui.FancyTextField email2;
    private fancyui.FancyTextField email3;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel7;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyTextField fullName;
    private fancyui.FancyButton registerBtn;
    private fancyui.FancyButton registerBtn1;
    private fancyui.FancyPasswordField registerPass;
    // End of variables declaration//GEN-END:variables
}
