
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    public Dashboard() {
        initComponents();
        loadUserData();
        setLocationRelativeTo(null);
        loadTransactions();   
    }
    private void loadUserData() {
        
        String sql = "SELECT users.fullname, accounts.account_number, accounts.balance FROM users JOIN accounts ON users.user_id = accounts.user_id WHERE users.user_id= ?";
        
       try (Connection conn = new DBconnection().connect(); PreparedStatement ps = conn.prepareStatement(sql)){
           ps.setInt(1, Session.userid);
           
           ResultSet rs = ps.executeQuery();
           
           if (rs.next()){
               String fullname = rs.getString("fullname");
               String accountNumber = rs.getString("account_number");
               double balance = rs.getDouble("balance");
               userName.setText(fullname);
               jlabelWelcome.setText("Welcome Back! " + fullname + "!");
               jlabelAccountNumber.setText(accountNumber);
               jlabelBalance.setText(String.format("₱%,.2f", balance));
           }
       } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
        
    }
    
    private void loadTransactions(){
        String sql = "SELECT transaction_type, description, date_time, amount, balance_after " + "FROM transactions WHERE user_id = ?" + "ORDER BY date_time DESC LIMIT 5";
        
        try (Connection conn = new DBconnection().connect(); PreparedStatement ps = conn.prepareStatement(sql)){  
            ps.setInt(1, Session.userid);
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel)transactionTableDashboard.getModel();
            model.setRowCount(0);
            
            while (rs.next()){
                model.addRow(new Object[]{
                rs.getString("transaction_type"),
                rs.getString("description"),
                rs.getString("date_time"),
                rs.getDouble("amount"),
                rs.getDouble("balance_after")
            });
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
            e.printStackTrace();
    }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fancyButton1 = new fancyui.FancyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fancyPanel5 = new fancyui.FancyPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        fancyLabel13 = new fancyui.FancyLabel();
        cardLayout = new fancyui.FancyPanel();
        fancyPanel4 = new fancyui.FancyPanel();
        fancyLabel4 = new fancyui.FancyLabel();
        fancyLabel6 = new fancyui.FancyLabel();
        jlabelAccountNumber = new fancyui.FancyLabel();
        fancyImage2 = new fancyui.FancyImage();
        fancyPanel2 = new fancyui.FancyPanel();
        jlabelBalance = new fancyui.FancyLabel();
        fancyPanel6 = new fancyui.FancyPanel();
        fancyLabel10 = new fancyui.FancyLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionTableDashboard = new fancyui.FancyTable();
        jpanelWithdraw = new fancyui.FancyPanel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel15 = new fancyui.FancyPanel();
        fancyImage4 = new fancyui.FancyImage();
        jpanelDeposit = new fancyui.FancyPanel();
        fancyPanel14 = new fancyui.FancyPanel();
        fancyImage3 = new fancyui.FancyImage();
        fancyLabel12 = new fancyui.FancyLabel();
        jlabelWelcome = new fancyui.FancyLabel();
        jLabel2 = new javax.swing.JLabel();
        profilee = new fancyui.FancyPanel();
        userName = new fancyui.FancyLabel();
        jpanelTransfer = new fancyui.FancyPanel();
        fancyLabel9 = new fancyui.FancyLabel();
        fancyPanel19 = new fancyui.FancyPanel();
        fancyImage6 = new fancyui.FancyImage();
        fancyPanel20 = new fancyui.FancyPanel();
        fancyImage8 = new fancyui.FancyImage();
        sideBtnDashboard = new fancyui.FancyButton();
        sideBtnDeposit = new fancyui.FancyButton();
        sideBtnTransfer = new fancyui.FancyButton();
        sideBtnWithdraw = new fancyui.FancyButton();
        sideBtnLogout = new fancyui.FancyButton();
        sideBtnProfile = new fancyui.FancyButton();
        sideBtnTransaction = new fancyui.FancyButton();

        fancyButton1.setText("fancyButton1");
        fancyButton1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        fancyButton1.addActionListener(this::fancyButton1ActionPerformed);

        fancyPanel5.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel5.setBorderEnabled(true);
        fancyPanel5.setBorderThickness(2.0F);
        fancyPanel5.setGradientAngle(65);
        fancyPanel5.setGradientEnd(new java.awt.Color(0, 0, 51));
        fancyPanel5.setGradientStart(new java.awt.Color(76, 0, 153));
        fancyPanel5.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        javax.swing.GroupLayout fancyPanel5Layout = new javax.swing.GroupLayout(fancyPanel5);
        fancyPanel5.setLayout(fancyPanel5Layout);
        fancyPanel5Layout.setHorizontalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        fancyPanel5Layout.setVerticalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        fancyLabel13.setText("fancyLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardLayout.setGradientEnabled(false);
        cardLayout.setGradientEnd(new java.awt.Color(0, 0, 20));
        cardLayout.setGradientStart(new java.awt.Color(0, 0, 51));
        cardLayout.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        cardLayout.setSolidBackgroundEnabled(true);

        fancyPanel4.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setBorderThickness(2.0F);
        fancyPanel4.setGradientAngle(65);
        fancyPanel4.setGradientEnd(new java.awt.Color(0, 0, 25));
        fancyPanel4.setGradientStart(new java.awt.Color(76, 0, 153));
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        fancyLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel4.setText("Current Balance");
        fancyLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        fancyLabel6.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fancyLabel6.setText("Account Number");
        fancyLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jlabelAccountNumber.setForeground(new java.awt.Color(255, 255, 255));
        jlabelAccountNumber.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-copy-24.png")); // NOI18N
        jlabelAccountNumber.setText("VB-2024-1001-5567");
        jlabelAccountNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        fancyImage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\veloracard.png")); // NOI18N

        fancyPanel2.setBorderColor(new java.awt.Color(102, 51, 255));
        fancyPanel2.setBorderEnabled(true);
        fancyPanel2.setGradientEnd(new java.awt.Color(204, 51, 255));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 51));

        jlabelBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlabelBalance.setForeground(new java.awt.Color(255, 255, 255));
        jlabelBalance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlabelBalance.setText(" ₱ 0.00");
        jlabelBalance.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlabelBalance.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fancyPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel4Layout.createSequentialGroup()
                        .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fancyPanel6.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel6.setBorderEnabled(true);
        fancyPanel6.setBorderThickness(2.0F);
        fancyPanel6.setGradientAngle(65);
        fancyPanel6.setGradientEnd(new java.awt.Color(0, 0, 51));
        fancyPanel6.setGradientStart(new java.awt.Color(76, 0, 153));
        fancyPanel6.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        fancyLabel10.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel10.setText("Recent Transactions");
        fancyLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        transactionTableDashboard.setAutoCreateRowSorter(true);
        transactionTableDashboard.setForeground(new java.awt.Color(255, 255, 255));
        transactionTableDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Deposit", "Cash Deposit", "05-12-25 - 10:30 AM", "+5,000.00", "25,750.00"},
                {"Withdraw", "ATM Withdrawal", "05-29-25 - 10:30 AM", "-2,000.00", "20,750.00"},
                {"Deposit", "Cash Deposit", "05-15-25 - 10:30 AM", "+3,000.00", "22,750.00"},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Description", "Date & Time", "Amount", "Balance After"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionTableDashboard.setAlignmentX(1.0F);
        transactionTableDashboard.setAlignmentY(1.0F);
        transactionTableDashboard.setColumnSelectionAllowed(true);
        transactionTableDashboard.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        transactionTableDashboard.setSelectionBackground(new java.awt.Color(0, 0, 51));
        transactionTableDashboard.setEvenRowColor(new java.awt.Color(31, 0, 63));
        transactionTableDashboard.setGradientEnabled(true);
        transactionTableDashboard.setGradientEnd(new java.awt.Color(51, 0, 153));
        transactionTableDashboard.setGradientStart(new java.awt.Color(0, 0, 51));
        transactionTableDashboard.setGridLineColor(new java.awt.Color(0, 0, 51));
        transactionTableDashboard.setHeaderBackground(new java.awt.Color(0, 0, 51));
        transactionTableDashboard.setHeaderForeground(new java.awt.Color(255, 255, 255));
        transactionTableDashboard.setOddRowColor(new java.awt.Color(51, 0, 51));
        transactionTableDashboard.setStripedRowsEnabled(true);
        transactionTableDashboard.setTableBackgroundColor(new java.awt.Color(39, 7, 81));
        jScrollPane2.setViewportView(transactionTableDashboard);
        transactionTableDashboard.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpanelWithdraw.setBorderColor(new java.awt.Color(102, 102, 102));
        jpanelWithdraw.setBorderEnabled(true);
        jpanelWithdraw.setBorderThickness(2.0F);
        jpanelWithdraw.setGradientAngle(65);
        jpanelWithdraw.setGradientEnd(new java.awt.Color(0, 0, 51));
        jpanelWithdraw.setGradientStart(new java.awt.Color(76, 0, 153));
        jpanelWithdraw.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        jpanelWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelWithdrawMouseClicked(evt);
            }
        });

        fancyLabel3.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel3.setText("Withdraw");
        fancyLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        fancyPanel15.setGradientEnd(new java.awt.Color(153, 102, 0));
        fancyPanel15.setGradientStart(new java.awt.Color(102, 51, 0));

        fancyImage4.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-up-50.png")); // NOI18N
        fancyImage4.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        javax.swing.GroupLayout fancyPanel15Layout = new javax.swing.GroupLayout(fancyPanel15);
        fancyPanel15.setLayout(fancyPanel15Layout);
        fancyPanel15Layout.setHorizontalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel15Layout.setVerticalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanelWithdrawLayout = new javax.swing.GroupLayout(jpanelWithdraw);
        jpanelWithdraw.setLayout(jpanelWithdrawLayout);
        jpanelWithdrawLayout.setHorizontalGroup(
            jpanelWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelWithdrawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpanelWithdrawLayout.setVerticalGroup(
            jpanelWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelWithdrawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpanelWithdrawLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelDeposit.setBorderColor(new java.awt.Color(102, 102, 102));
        jpanelDeposit.setBorderEnabled(true);
        jpanelDeposit.setBorderThickness(2.0F);
        jpanelDeposit.setGradientAngle(65);
        jpanelDeposit.setGradientEnd(new java.awt.Color(0, 0, 51));
        jpanelDeposit.setGradientStart(new java.awt.Color(76, 0, 153));
        jpanelDeposit.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        jpanelDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelDepositMouseClicked(evt);
            }
        });

        fancyPanel14.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel14.setGradientStart(new java.awt.Color(118, 32, 204));

        fancyImage3.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-down-50.png")); // NOI18N
        fancyImage3.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        javax.swing.GroupLayout fancyPanel14Layout = new javax.swing.GroupLayout(fancyPanel14);
        fancyPanel14.setLayout(fancyPanel14Layout);
        fancyPanel14Layout.setHorizontalGroup(
            fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel14Layout.setVerticalGroup(
            fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyLabel12.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel12.setText("Deposit");
        fancyLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        javax.swing.GroupLayout jpanelDepositLayout = new javax.swing.GroupLayout(jpanelDeposit);
        jpanelDeposit.setLayout(jpanelDepositLayout);
        jpanelDepositLayout.setHorizontalGroup(
            jpanelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jpanelDepositLayout.setVerticalGroup(
            jpanelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpanelDepositLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jlabelWelcome.setForeground(new java.awt.Color(255, 204, 0));
        jlabelWelcome.setText("Welcome Back");
        jlabelWelcome.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here's what's happening to your account today.");

        profilee.setGradientEnd(new java.awt.Color(125, 24, 175));
        profilee.setGradientStart(new java.awt.Color(0, 0, 51));
        profilee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileeMouseClicked(evt);
            }
        });

        userName.setForeground(new java.awt.Color(255, 204, 0));
        userName.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-user-24 (1).png")); // NOI18N
        userName.setText("User");
        userName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        javax.swing.GroupLayout profileeLayout = new javax.swing.GroupLayout(profilee);
        profilee.setLayout(profileeLayout);
        profileeLayout.setHorizontalGroup(
            profileeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileeLayout.setVerticalGroup(
            profileeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpanelTransfer.setBorderColor(new java.awt.Color(102, 102, 102));
        jpanelTransfer.setBorderEnabled(true);
        jpanelTransfer.setBorderThickness(2.0F);
        jpanelTransfer.setGradientAngle(65);
        jpanelTransfer.setGradientEnd(new java.awt.Color(0, 0, 51));
        jpanelTransfer.setGradientStart(new java.awt.Color(76, 0, 153));
        jpanelTransfer.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        jpanelTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelTransferMouseClicked(evt);
            }
        });

        fancyLabel9.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel9.setText("Transfer");
        fancyLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        fancyPanel19.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel19.setGradientStart(new java.awt.Color(118, 32, 204));

        fancyImage6.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-transfer-100 (1).png")); // NOI18N
        fancyImage6.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        javax.swing.GroupLayout fancyPanel19Layout = new javax.swing.GroupLayout(fancyPanel19);
        fancyPanel19.setLayout(fancyPanel19Layout);
        fancyPanel19Layout.setHorizontalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel19Layout.setVerticalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanelTransferLayout = new javax.swing.GroupLayout(jpanelTransfer);
        jpanelTransfer.setLayout(jpanelTransferLayout);
        jpanelTransferLayout.setHorizontalGroup(
            jpanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpanelTransferLayout.setVerticalGroup(
            jpanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpanelTransferLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyPanel20.setBorderEnabled(true);
        fancyPanel20.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel20.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyImage8.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\ChatGPT Image Sep 24, 2026, 04_56_03 PM.png")); // NOI18N
        fancyImage8.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        sideBtnDashboard.setText("Dashboard");
        sideBtnDashboard.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnDashboard.setBorderThickness(3.0F);
        sideBtnDashboard.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnDashboard.addActionListener(this::sideBtnDashboardActionPerformed);

        sideBtnDeposit.setText("Deposit");
        sideBtnDeposit.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnDeposit.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnDeposit.setBorderThickness(3.0F);
        sideBtnDeposit.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnDeposit.addActionListener(this::sideBtnDepositActionPerformed);

        sideBtnTransfer.setText("Transfer");
        sideBtnTransfer.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnTransfer.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnTransfer.setBorderThickness(3.0F);
        sideBtnTransfer.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnTransfer.addActionListener(this::sideBtnTransferfancyButton4ActionPerformed);

        sideBtnWithdraw.setText("Withdraw");
        sideBtnWithdraw.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnWithdraw.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnWithdraw.setBorderThickness(3.0F);
        sideBtnWithdraw.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnWithdraw.addActionListener(this::sideBtnWithdrawfancyButton5ActionPerformed);

        sideBtnLogout.setText("Logout");
        sideBtnLogout.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnLogout.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnLogout.setBorderThickness(3.0F);
        sideBtnLogout.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnLogout.addActionListener(this::sideBtnLogoutActionPerformed);

        sideBtnProfile.setText("Profile");
        sideBtnProfile.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnProfile.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnProfile.setBorderThickness(3.0F);
        sideBtnProfile.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnProfile.addActionListener(this::sideBtnProfilefancyButton6ActionPerformed);

        sideBtnTransaction.setText("Transaction  History");
        sideBtnTransaction.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnTransaction.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnTransaction.setBorderThickness(3.0F);
        sideBtnTransaction.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnTransaction.addActionListener(this::sideBtnTransactionfancyButton5ActionPerformed);

        javax.swing.GroupLayout fancyPanel20Layout = new javax.swing.GroupLayout(fancyPanel20);
        fancyPanel20.setLayout(fancyPanel20Layout);
        fancyPanel20Layout.setHorizontalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sideBtnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnWithdraw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnTransaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addComponent(sideBtnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fancyPanel20Layout.setVerticalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sideBtnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sideBtnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout cardLayoutLayout = new javax.swing.GroupLayout(cardLayout);
        cardLayout.setLayout(cardLayoutLayout);
        cardLayoutLayout.setHorizontalGroup(
            cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardLayoutLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profilee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(fancyPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addComponent(jpanelDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jpanelWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jpanelTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        cardLayoutLayout.setVerticalGroup(
            cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayoutLayout.createSequentialGroup()
                .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jlabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cardLayoutLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profilee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(fancyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpanelWithdraw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelDeposit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addComponent(fancyPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(cardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton1ActionPerformed

    private void sideBtnTransferfancyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnTransferfancyButton4ActionPerformed
     new Transfer().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sideBtnTransferfancyButton4ActionPerformed

    private void sideBtnWithdrawfancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnWithdrawfancyButton5ActionPerformed
     new Withdraw().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sideBtnWithdrawfancyButton5ActionPerformed

    private void sideBtnProfilefancyButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnProfilefancyButton6ActionPerformed
      new profilePage().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_sideBtnProfilefancyButton6ActionPerformed

    private void sideBtnTransactionfancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnTransactionfancyButton5ActionPerformed
     new TransactionHistory().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sideBtnTransactionfancyButton5ActionPerformed

    private void jpanelDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelDepositMouseClicked
        new Deposit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpanelDepositMouseClicked

    private void jpanelWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelWithdrawMouseClicked
      new Withdraw().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jpanelWithdrawMouseClicked

    private void jpanelTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelTransferMouseClicked
       new Transfer().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jpanelTransferMouseClicked

    private void profileeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileeMouseClicked
      new profilePage().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_profileeMouseClicked

    private void sideBtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnDashboardActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sideBtnDashboardActionPerformed

    private void sideBtnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnDepositActionPerformed
     new Deposit().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sideBtnDepositActionPerformed

    private void sideBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnLogoutActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "You have been logged out.");
        new demoframe().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_sideBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyPanel cardLayout;
    private fancyui.FancyButton fancyButton1;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyImage fancyImage3;
    private fancyui.FancyImage fancyImage4;
    private fancyui.FancyImage fancyImage6;
    private fancyui.FancyImage fancyImage8;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyLabel fancyLabel13;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel14;
    private fancyui.FancyPanel fancyPanel15;
    private fancyui.FancyPanel fancyPanel19;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel20;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel5;
    private fancyui.FancyPanel fancyPanel6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private fancyui.FancyLabel jlabelAccountNumber;
    private fancyui.FancyLabel jlabelBalance;
    private fancyui.FancyLabel jlabelWelcome;
    private fancyui.FancyPanel jpanelDeposit;
    private fancyui.FancyPanel jpanelTransfer;
    private fancyui.FancyPanel jpanelWithdraw;
    private fancyui.FancyPanel profilee;
    private fancyui.FancyButton sideBtnDashboard;
    private fancyui.FancyButton sideBtnDeposit;
    private fancyui.FancyButton sideBtnLogout;
    private fancyui.FancyButton sideBtnProfile;
    private fancyui.FancyButton sideBtnTransaction;
    private fancyui.FancyButton sideBtnTransfer;
    private fancyui.FancyButton sideBtnWithdraw;
    private fancyui.FancyTable transactionTableDashboard;
    private fancyui.FancyLabel userName;
    // End of variables declaration//GEN-END:variables

    
}
