import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

public class Deposit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deposit.class.getName());

    public Deposit() {
        initComponents();
        setLocationRelativeTo(null);
        loadBalance();
        paymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Payment Method", "Cash", "GCash", "Bank Transfer", "Check"}));
        userNAme.setText(Session.fullname);
    }
    
    private void loadBalance() {

    String sql = "SELECT balance FROM accounts WHERE user_id = ?";

    try (Connection conn = new DBconnection().connect();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setInt(1, Session.userid);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            double balance = rs.getDouble("balance");
            jlabelBalance.setText(String.format("₱%,.2f", balance));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Unable to load balance: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fancyTextField2 = new fancyui.FancyTextField();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel21 = new fancyui.FancyPanel();
        fancyPanel20 = new fancyui.FancyPanel();
        fancyImage8 = new fancyui.FancyImage();
        sideBtnDashboard = new fancyui.FancyButton();
        sideBtnDeposit1 = new fancyui.FancyButton();
        sideBtnTransfer1 = new fancyui.FancyButton();
        sideBtnWithdraw1 = new fancyui.FancyButton();
        logoutBtn = new fancyui.FancyButton();
        sideBtnProfile1 = new fancyui.FancyButton();
        sideBtnTransactionHistory1 = new fancyui.FancyButton();
        fancyPanel6 = new fancyui.FancyPanel();
        fancyPanel4 = new fancyui.FancyPanel();
        fancyLabel5 = new fancyui.FancyLabel();
        fancyPanel22 = new fancyui.FancyPanel();
        jLabel4 = new javax.swing.JLabel();
        jlabelBalance = new fancyui.FancyLabel();
        fancyImage11 = new fancyui.FancyImage();
        fancyPanel5 = new fancyui.FancyPanel();
        fancyLabel2 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        depTextField = new fancyui.FancyTextField();
        paymentComboBox = new javax.swing.JComboBox<>();
        depBtn = new fancyui.FancyButton();
        fancyLabel4 = new fancyui.FancyLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profilebtn2 = new fancyui.FancyPanel();
        userNAme = new fancyui.FancyLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel21.setGradientEnabled(false);
        fancyPanel21.setGradientEnd(new java.awt.Color(0, 0, 20));
        fancyPanel21.setGradientStart(new java.awt.Color(0, 0, 51));
        fancyPanel21.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        fancyPanel21.setSolidBackgroundEnabled(true);

        fancyPanel20.setBorderEnabled(true);
        fancyPanel20.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel20.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyImage8.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\ChatGPT Image Sep 24, 2026, 04_56_03 PM.png")); // NOI18N
        fancyImage8.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        sideBtnDashboard.setText("Dashboard");
        sideBtnDashboard.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnDashboard.setBorderThickness(3.0F);
        sideBtnDashboard.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnDashboard.addActionListener(this::sideBtnDashboardActionPerformed);

        sideBtnDeposit1.setText("Deposit");
        sideBtnDeposit1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnDeposit1.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnDeposit1.setBorderThickness(3.0F);
        sideBtnDeposit1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnDeposit1.addActionListener(this::sideBtnDeposit1ActionPerformed);

        sideBtnTransfer1.setText("Transfer");
        sideBtnTransfer1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnTransfer1.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnTransfer1.setBorderThickness(3.0F);
        sideBtnTransfer1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnTransfer1.addActionListener(this::fancyButton4ActionPerformed);

        sideBtnWithdraw1.setText("Withdraw");
        sideBtnWithdraw1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnWithdraw1.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnWithdraw1.setBorderThickness(3.0F);
        sideBtnWithdraw1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnWithdraw1.addActionListener(this::fancyButton5ActionPerformed);

        logoutBtn.setText("Logout");
        logoutBtn.setBackgroundColor(new java.awt.Color(0, 0, 51));
        logoutBtn.setBorderColor(new java.awt.Color(153, 153, 153));
        logoutBtn.setBorderThickness(3.0F);
        logoutBtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        sideBtnProfile1.setText("Profile");
        sideBtnProfile1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnProfile1.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnProfile1.setBorderThickness(3.0F);
        sideBtnProfile1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnProfile1.addActionListener(this::fancyButton6ActionPerformed);

        sideBtnTransactionHistory1.setText("Transaction  History");
        sideBtnTransactionHistory1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        sideBtnTransactionHistory1.setBorderColor(new java.awt.Color(153, 153, 153));
        sideBtnTransactionHistory1.setBorderThickness(3.0F);
        sideBtnTransactionHistory1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        sideBtnTransactionHistory1.addActionListener(this::sideBtnTransactionHistory1fancyButton5ActionPerformed);

        javax.swing.GroupLayout fancyPanel20Layout = new javax.swing.GroupLayout(fancyPanel20);
        fancyPanel20.setLayout(fancyPanel20Layout);
        fancyPanel20Layout.setHorizontalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sideBtnWithdraw1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnTransfer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnDeposit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnTransactionHistory1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBtnProfile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fancyPanel20Layout.setVerticalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sideBtnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnDeposit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnWithdraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBtnTransactionHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sideBtnProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        fancyPanel6.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel6.setBorderEnabled(true);
        fancyPanel6.setBorderThickness(2.0F);
        fancyPanel6.setGradientAngle(65);
        fancyPanel6.setGradientEnd(new java.awt.Color(0, 0, 25));
        fancyPanel6.setGradientStart(new java.awt.Color(18, 0, 38));
        fancyPanel6.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setGradientEnd(new java.awt.Color(25, 0, 56));
        fancyPanel4.setGradientStart(new java.awt.Color(76, 0, 153));

        fancyLabel5.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel5.setText("Deposit to Your Account");
        fancyLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N

        fancyPanel22.setBorderColor(new java.awt.Color(0, 0, 12));
        fancyPanel22.setBorderEnabled(true);
        fancyPanel22.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel22.setGradientStart(new java.awt.Color(118, 32, 204));
        fancyPanel22.setSolidBackgroundColor(new java.awt.Color(7, 0, 28));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Balance");

        jlabelBalance.setForeground(new java.awt.Color(51, 255, 51));
        jlabelBalance.setText("₱25,750.00");
        jlabelBalance.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        javax.swing.GroupLayout fancyPanel22Layout = new javax.swing.GroupLayout(fancyPanel22);
        fancyPanel22.setLayout(fancyPanel22Layout);
        fancyPanel22Layout.setHorizontalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addGroup(fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel22Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel22Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jlabelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        fancyPanel22Layout.setVerticalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        fancyImage11.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-scroll-down-64.png")); // NOI18N

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(fancyImage11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(fancyPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyPanel5.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyPanel5.setBorderEnabled(true);
        fancyPanel5.setBottomLeftRadius(0);
        fancyPanel5.setGradientEnd(new java.awt.Color(16, 0, 25));
        fancyPanel5.setGradientStart(new java.awt.Color(76, 0, 163));
        fancyPanel5.setTopLeftRadius(0);

        fancyLabel3.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel3.setText("Payment Method");
        fancyLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N

        depTextField.setCornerRadius(8);
        depTextField.setIconTextGap(12);
        depTextField.setPlaceholder("0.00");
        depTextField.addActionListener(this::depTextFieldActionPerformed);

        paymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paymentComboBox.addActionListener(this::paymentComboBoxActionPerformed);

        depBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        depBtn.setText("Deposit");
        depBtn.setBorderThickness(0.0F);
        depBtn.setCornerRadius(6);
        depBtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        depBtn.setGradientAngle(95);
        depBtn.setGradientEnabled(true);
        depBtn.setGradientEnd(new java.awt.Color(8, 0, 17));
        depBtn.setGradientStart(new java.awt.Color(102, 51, 255));
        depBtn.addActionListener(this::depBtnActionPerformed);

        fancyLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel4.setText("Enter Deposit Amount");
        fancyLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your balance will be updated after a successful deposit.");

        javax.swing.GroupLayout fancyPanel5Layout = new javax.swing.GroupLayout(fancyPanel5);
        fancyPanel5.setLayout(fancyPanel5Layout);
        fancyPanel5Layout.setHorizontalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addGroup(fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(paymentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fancyPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        fancyPanel5Layout.setVerticalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(depTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(depBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(fancyPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(fancyPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(fancyPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deposit");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add money to your account securely.");

        profilebtn2.setGradientEnd(new java.awt.Color(125, 24, 175));
        profilebtn2.setGradientStart(new java.awt.Color(0, 0, 51));
        profilebtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilebtn2MouseClicked(evt);
            }
        });

        userNAme.setForeground(new java.awt.Color(255, 204, 0));
        userNAme.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-user-24 (1).png")); // NOI18N
        userNAme.setText("Jasper Arenas");
        userNAme.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        userNAme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNAmeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilebtn2Layout = new javax.swing.GroupLayout(profilebtn2);
        profilebtn2.setLayout(profilebtn2Layout);
        profilebtn2Layout.setHorizontalGroup(
            profilebtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilebtn2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(userNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profilebtn2Layout.setVerticalGroup(
            profilebtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilebtn2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userNAme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel21Layout = new javax.swing.GroupLayout(fancyPanel21);
        fancyPanel21.setLayout(fancyPanel21Layout);
        fancyPanel21Layout.setHorizontalGroup(
            fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel21Layout.createSequentialGroup()
                .addComponent(fancyPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel21Layout.createSequentialGroup()
                        .addGroup(fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel21Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fancyPanel21Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profilebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(fancyPanel21Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(fancyPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        fancyPanel21Layout.setVerticalGroup(
            fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel21Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fancyPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2))
                    .addComponent(profilebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(fancyPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addComponent(fancyPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton6ActionPerformed
    new profilePage().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_fancyButton6ActionPerformed

    private void fancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton5ActionPerformed
      new Withdraw().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_fancyButton5ActionPerformed

    private void fancyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton4ActionPerformed
     new Transfer().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_fancyButton4ActionPerformed

    private void depTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depTextFieldActionPerformed

    private void sideBtnTransactionHistory1fancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnTransactionHistory1fancyButton5ActionPerformed
        new TransactionHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sideBtnTransactionHistory1fancyButton5ActionPerformed

    private void sideBtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnDashboardActionPerformed
     new Dashboard().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sideBtnDashboardActionPerformed

    private void profilebtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtn2MouseClicked
     new profilePage().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_profilebtn2MouseClicked

    private void sideBtnDeposit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBtnDeposit1ActionPerformed
    new Deposit().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_sideBtnDeposit1ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "You have been logged out.");

        new demoframe().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void depBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depBtnActionPerformed
    String text = depTextField.getText().trim();
    if (text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter deposit amount.");
        return;
    }
    double amount;

    try {
        amount = Double.parseDouble(text);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid amount.");
        return;
    }

    if (amount <= 0) {
        JOptionPane.showMessageDialog(this, "Amount must be greater than ₱0.");
        return;
    }
    String method = paymentComboBox.getSelectedItem().toString();

    if (method.equals("Select Payment Method")) {
        JOptionPane.showMessageDialog(this, "Select a payment method.");
        return;
    }
    JPasswordField pinField = new JPasswordField();

    if (JOptionPane.showConfirmDialog(
            this, pinField, "Enter PIN",
            JOptionPane.OK_CANCEL_OPTION) != JOptionPane.OK_OPTION) {
        return;
    }
    String pin = new String(pinField.getPassword());

    try (Connection con = new DBconnection().connect()) {

        PreparedStatement ps = con.prepareStatement("SELECT pin, balance FROM users u " + "JOIN accounts a ON u.user_id=a.user_id " + "WHERE u.user_id=?");
        ps.setInt(1, Session.userid);
        ResultSet rs = ps.executeQuery();

        if (!rs.next() || !pin.equals(rs.getString("pin"))) {
            JOptionPane.showMessageDialog(this, "Incorrect PIN.");
            return;
        }
        double newBalance = rs.getDouble("balance") + amount;
        ps = con.prepareStatement("UPDATE accounts SET balance=? WHERE user_id=?");

        ps.setDouble(1, newBalance);
        ps.setInt(2, Session.userid);
        ps.executeUpdate();

        ps = con.prepareStatement("INSERT INTO transactions " + "(user_id, transaction_type, description, amount, date_time, balance_after) " + "VALUES (?, ?, ?, ?, datetime('now','localtime'), ?)");
       
        ps.setInt(1, Session.userid);
        ps.setString(2, "Deposit");
        ps.setString(3, method + " Deposit");
        ps.setDouble(4, amount);
        ps.setDouble(5, newBalance);
        ps.executeUpdate();

        loadBalance();
        depTextField.setText("");
        paymentComboBox.setSelectedIndex(0);

        JOptionPane.showMessageDialog(this,
            String.format("Deposit successful \n\nPayment: %s\nAmount: ₱%,.2f", method, amount));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_depBtnActionPerformed

    private void paymentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentComboBoxActionPerformed
       
    }//GEN-LAST:event_paymentComboBoxActionPerformed

    private void userNAmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNAmeMouseClicked
       
    }//GEN-LAST:event_userNAmeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deposit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton depBtn;
    private fancyui.FancyTextField depTextField;
    private fancyui.FancyImage fancyImage11;
    private fancyui.FancyImage fancyImage8;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel20;
    private fancyui.FancyPanel fancyPanel21;
    private fancyui.FancyPanel fancyPanel22;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel5;
    private fancyui.FancyPanel fancyPanel6;
    private fancyui.FancyTextField fancyTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private fancyui.FancyLabel jlabelBalance;
    private fancyui.FancyButton logoutBtn;
    private javax.swing.JComboBox<String> paymentComboBox;
    private fancyui.FancyPanel profilebtn2;
    private fancyui.FancyButton sideBtnDashboard;
    private fancyui.FancyButton sideBtnDeposit1;
    private fancyui.FancyButton sideBtnProfile1;
    private fancyui.FancyButton sideBtnTransactionHistory1;
    private fancyui.FancyButton sideBtnTransfer1;
    private fancyui.FancyButton sideBtnWithdraw1;
    private fancyui.FancyLabel userNAme;
    // End of variables declaration//GEN-END:variables
}
