import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TransactionHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionHistory.class.getName());

    public TransactionHistory() {
        initComponents();
        setLocationRelativeTo(null);
        tUserLabel.setText(Session.fullname);     
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"All", "Deposit", "Withdraw", "Transfer"} ));
        loadTransactions();
}
    private void loadTransactions() {
    String filter = comboBox.getSelectedItem().toString();
    String query = "SELECT transaction_type, description, date_time, amount, balance_after " + "FROM transactions WHERE user_id = ?";

    if (!filter.equals("All")) {
        query += " AND transaction_type = ?";
    }
    query += " ORDER BY date_time DESC";

    try (Connection conn = new DBconnection().connect();
         PreparedStatement ps = conn.prepareStatement(query)) {

        ps.setInt(1, Session.userid);

        if (!filter.equals("All")) {
            ps.setString(2, filter);
        }
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) fancyTable1.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("transaction_type"),
                rs.getString("description"),
                rs.getString("date_time"),
                rs.getDouble("amount"),
                rs.getDouble("balance_after")});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        fancyButton12 = new fancyui.FancyButton();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel6 = new fancyui.FancyPanel();
        fancyLabel10 = new fancyui.FancyLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fancyTable1 = new fancyui.FancyTable();
        fancyLabel1 = new fancyui.FancyLabel();
        jLabel2 = new javax.swing.JLabel();
        fancyPanel10 = new fancyui.FancyPanel();
        tUserLabel = new fancyui.FancyLabel();
        fancyPanel2 = new fancyui.FancyPanel();
        comboBox = new javax.swing.JComboBox<>();
        fancyLabel12 = new fancyui.FancyLabel();
        fancyPanel22 = new fancyui.FancyPanel();
        fancyImage10 = new fancyui.FancyImage();
        dashboard = new fancyui.FancyButton();
        deposit = new fancyui.FancyButton();
        transfer = new fancyui.FancyButton();
        withdraw = new fancyui.FancyButton();
        fancyButton60 = new fancyui.FancyButton();
        fancyButton61 = new fancyui.FancyButton();
        withdraw1 = new fancyui.FancyButton();

        jCheckBox1.setText("jCheckBox1");

        fancyButton12.setText("fancyButton9");
        fancyButton12.setBackgroundColor(new java.awt.Color(0, 0, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setGradientEnabled(false);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 20));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 51));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyPanel6.setBorderColor(new java.awt.Color(102, 102, 102));
        fancyPanel6.setBorderEnabled(true);
        fancyPanel6.setBorderThickness(2.0F);
        fancyPanel6.setGradientAngle(65);
        fancyPanel6.setGradientEnd(new java.awt.Color(0, 0, 51));
        fancyPanel6.setGradientStart(new java.awt.Color(76, 0, 153));
        fancyPanel6.setSolidBackgroundColor(new java.awt.Color(0, 0, 25));

        fancyLabel10.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel10.setText("Recent Transactions");
        fancyLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        fancyTable1.setAutoCreateRowSorter(true);
        fancyTable1.setForeground(new java.awt.Color(255, 255, 255));
        fancyTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Deposit", "Cash Deposit", "05-12-25 - 10:30 AM", "+5,000.00", "25,750.00"},
                {"Withdraw", "ATM Withdrawal", "05-29-25 - 10:30 AM", "-2,000.00", "20,750.00"},
                {"Deposit", "Cash Deposit", "05-15-25 - 10:30 AM", "+3,000.00", "22,750.00"},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Description", "Date & Time", "Amount", "Balance After"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fancyTable1.setAlignmentX(1.0F);
        fancyTable1.setAlignmentY(1.0F);
        fancyTable1.setColumnSelectionAllowed(true);
        fancyTable1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        fancyTable1.setSelectionBackground(new java.awt.Color(0, 0, 51));
        fancyTable1.setEvenRowColor(new java.awt.Color(31, 0, 63));
        fancyTable1.setGradientEnabled(true);
        fancyTable1.setGradientEnd(new java.awt.Color(51, 0, 153));
        fancyTable1.setGradientStart(new java.awt.Color(0, 0, 51));
        fancyTable1.setGridLineColor(new java.awt.Color(0, 0, 51));
        fancyTable1.setHeaderBackground(new java.awt.Color(0, 0, 51));
        fancyTable1.setHeaderForeground(new java.awt.Color(255, 255, 255));
        fancyTable1.setOddRowColor(new java.awt.Color(51, 0, 51));
        fancyTable1.setStripedRowsEnabled(true);
        fancyTable1.setTableBackgroundColor(new java.awt.Color(39, 7, 81));
        jScrollPane2.setViewportView(fancyTable1);

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 557, Short.MAX_VALUE))
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyLabel1.setForeground(new java.awt.Color(255, 204, 0));
        fancyLabel1.setText("Transaction History");
        fancyLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here are all your recent transactions.");

        fancyPanel10.setGradientEnd(new java.awt.Color(125, 24, 175));
        fancyPanel10.setGradientStart(new java.awt.Color(0, 0, 51));
        fancyPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fancyPanel10MouseClicked(evt);
            }
        });

        tUserLabel.setForeground(new java.awt.Color(255, 204, 0));
        tUserLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\icons8-user-24 (1).png")); // NOI18N
        tUserLabel.setText("Jasper Arenas");
        tUserLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel10Layout = new javax.swing.GroupLayout(fancyPanel10);
        fancyPanel10.setLayout(fancyPanel10Layout);
        fancyPanel10Layout.setHorizontalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel10Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(tUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fancyPanel10Layout.setVerticalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 51));
        fancyPanel2.setGradientStart(new java.awt.Color(76, 0, 153));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox.addActionListener(this::comboBoxActionPerformed);

        fancyLabel12.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel12.setText("Filter by");
        fancyLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyPanel22.setBorderEnabled(true);
        fancyPanel22.setGradientEnd(new java.awt.Color(51, 0, 102));
        fancyPanel22.setGradientStart(new java.awt.Color(0, 0, 51));

        fancyImage10.setIcon(new javax.swing.ImageIcon("C:\\Users\\p_gen\\Downloads\\ChatGPT Image Sep 24, 2026, 04_56_03 PM.png")); // NOI18N
        fancyImage10.setScaleType(fancyui.FancyImage.ScaleType.STRETCH);

        dashboard.setText("Dashboard");
        dashboard.setBackgroundColor(new java.awt.Color(0, 0, 51));
        dashboard.setBorderThickness(3.0F);
        dashboard.setDefaultForeground(new java.awt.Color(255, 255, 255));
        dashboard.addActionListener(this::dashboardActionPerformed);

        deposit.setText("Deposit");
        deposit.setBackgroundColor(new java.awt.Color(0, 0, 51));
        deposit.setBorderColor(new java.awt.Color(153, 153, 153));
        deposit.setBorderThickness(3.0F);
        deposit.setDefaultForeground(new java.awt.Color(255, 255, 255));
        deposit.addActionListener(this::depositActionPerformed);

        transfer.setText("Transfer");
        transfer.setBackgroundColor(new java.awt.Color(0, 0, 51));
        transfer.setBorderColor(new java.awt.Color(153, 153, 153));
        transfer.setBorderThickness(3.0F);
        transfer.setDefaultForeground(new java.awt.Color(255, 255, 255));
        transfer.addActionListener(this::transferfancyButton4ActionPerformed);

        withdraw.setText("Withdraw");
        withdraw.setBackgroundColor(new java.awt.Color(0, 0, 51));
        withdraw.setBorderColor(new java.awt.Color(153, 153, 153));
        withdraw.setBorderThickness(3.0F);
        withdraw.setDefaultForeground(new java.awt.Color(255, 255, 255));
        withdraw.addActionListener(this::withdrawfancyButton5ActionPerformed);

        fancyButton60.setText("Logout");
        fancyButton60.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton60.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyButton60.setBorderThickness(3.0F);
        fancyButton60.setDefaultForeground(new java.awt.Color(255, 255, 255));
        fancyButton60.addActionListener(this::fancyButton60ActionPerformed);

        fancyButton61.setText("Profile");
        fancyButton61.setBackgroundColor(new java.awt.Color(0, 0, 51));
        fancyButton61.setBorderColor(new java.awt.Color(153, 153, 153));
        fancyButton61.setBorderThickness(3.0F);
        fancyButton61.setDefaultForeground(new java.awt.Color(255, 255, 255));
        fancyButton61.addActionListener(this::fancyButton61fancyButton6ActionPerformed);

        withdraw1.setText("Transaction  History");
        withdraw1.setBackgroundColor(new java.awt.Color(0, 0, 51));
        withdraw1.setBorderColor(new java.awt.Color(153, 153, 153));
        withdraw1.setBorderThickness(3.0F);
        withdraw1.setDefaultForeground(new java.awt.Color(255, 255, 255));
        withdraw1.addActionListener(this::withdraw1fancyButton5ActionPerformed);

        javax.swing.GroupLayout fancyPanel22Layout = new javax.swing.GroupLayout(fancyPanel22);
        fancyPanel22.setLayout(fancyPanel22Layout);
        fancyPanel22Layout.setHorizontalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(withdraw1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fancyButton61, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fancyButton60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fancyPanel22Layout.setVerticalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addComponent(fancyImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(213, 213, 213)
                        .addComponent(fancyPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addComponent(fancyPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        loadTransactions();
    }//GEN-LAST:event_comboBoxActionPerformed

    private void transferfancyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferfancyButton4ActionPerformed
     new Transfer().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_transferfancyButton4ActionPerformed

    private void withdrawfancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawfancyButton5ActionPerformed
     new Withdraw().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_withdrawfancyButton5ActionPerformed

    private void fancyButton61fancyButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton61fancyButton6ActionPerformed
     new profilePage().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_fancyButton61fancyButton6ActionPerformed

    private void withdraw1fancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw1fancyButton5ActionPerformed
     new TransactionHistory().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_withdraw1fancyButton5ActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
      new Dashboard().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
      new Deposit().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_depositActionPerformed

    private void fancyPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fancyPanel10MouseClicked
      new profilePage().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_fancyPanel10MouseClicked

    private void fancyButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton60ActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {

        JOptionPane.showMessageDialog(this, "You have been logged out.");

        new demoframe().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_fancyButton60ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private fancyui.FancyButton dashboard;
    private fancyui.FancyButton deposit;
    private fancyui.FancyButton fancyButton12;
    private fancyui.FancyButton fancyButton60;
    private fancyui.FancyButton fancyButton61;
    private fancyui.FancyImage fancyImage10;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel10;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel22;
    private fancyui.FancyPanel fancyPanel6;
    private fancyui.FancyTable fancyTable1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private fancyui.FancyLabel tUserLabel;
    private fancyui.FancyButton transfer;
    private fancyui.FancyButton withdraw;
    private fancyui.FancyButton withdraw1;
    // End of variables declaration//GEN-END:variables
}
